# Generated by Django 5.2.4 on 2025-07-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="task",
            new_name="user",
        ),
    ]
